version: '3.7'

networks:
  network: {}

services:
  database:
    container_name: stingy-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "stingydb"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "123456"
    ports:
      - 3306:3306
    networks:
      - network
    restart: always

